version: "2"
services:
  web:
    build: .
    command: node index.js
    ports:
      - "8080:8080"
    environment:
      - awsAccessKeyId=${awsAccessKeyId}
      - awsSecretAccessKey=${awsSecretAccessKey}
      - awsDefaultRegion=${awsDefaultRegion}
      - environment=${environment}
